# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=6)),
                ('district', models.DecimalField(decimal_places=0, max_digits=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.CharField(max_length=30)),
                ('office', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('advance_date', models.DateField()),
                ('scrapped_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
