# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(max_length=6)),
                ('district', models.DecimalField(decimal_places=0, max_digits=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.CharField(max_length=30)),
                ('office', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('advance_date', models.DateField()),
                ('scrapped_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='advance_date',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='office',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='scrapped_date',
        ),
        migrations.RemoveField(
            model_name='letproject',
            name='url',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='agreement_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.LetProject'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='prime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asPrime', to='partners.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asSub', to='partners.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='letproject',
            name='second_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seconds', to='partners.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='letproject',
            name='third_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirds', to='partners.BusinessPartner'),
        ),
        migrations.AddField(
            model_name='letproject',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='partners.BusinessPartner'),
        ),
    ]
