# Generated by Django 2.0.2 on 2018-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letproject',
            name='scrapped_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
