# Generated by Django 2.0.2 on 2018-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_letproject_scrapped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='letproject',
            name='let_date',
            field=models.DateField(default='2017-12-31'),
        ),
    ]
