# Generated by Django 2.0.2 on 2018-03-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='overtime_hours_budget',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='project',
            name='straight_hours_budget',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=9),
        ),
    ]
