# Generated by Django 2.0.2 on 2018-05-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('return_date', models.DateField(blank=True, help_text='leave blank if item is still out', null=True)),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='i.e. kopfield1', max_length=60)),
                ('office', models.CharField(choices=[('King of Prussia', 'KOP'), ('Pittsburgh', 'PGH'), ('Test', 'TEST'), ('None', 'None')], default='King of Prussia', max_length=30)),
                ('device', models.CharField(choices=[('iPhone', 'iPhone'), ('iPad', 'iPad'), ('Laptop', 'Laptop')], max_length=35)),
                ('serial_number', models.CharField(max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspectors.Inspector'),
        ),
    ]
