# Generated by Django 2.0.2 on 2018-09-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
