# Generated by Django 2.0.2 on 2018-03-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('straight_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('invoice_number', models.DecimalField(blank=True, decimal_places=0, help_text='Prudent invoice number i.e. 17176', max_digits=5, null=True)),
                ('invoice_file', models.FileField(upload_to='', verbose_name='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'AWAITING MANAGER APPROVAL'), (2, 'AWAITING REVIEWER APPROVAL'), (3, 'APPROVED FOR SUBMISSION')], default=0)),
                ('last_modified', models.DateField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
