# Generated by Django 2.0.2 on 2018-03-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (1, 'AWAITING MANAGER APPROVAL'), (2, 'AWAITING REVIEWER APPROVAL'), (3, 'APPROVED FOR SUBMISSION')], default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(upload_to='', verbose_name='invoices'),
        ),
    ]
