# Generated by Django 2.0.2 on 2018-03-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_auto_20180301_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
