# Generated by Django 2.0.2 on 2018-05-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='resume_file',
        ),
    ]
