# Generated by Django 2.0.2 on 2018-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='district_10_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_11_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_12_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_1_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_2_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_3_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_4_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_5_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_6_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_8_experience',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='district_9_experience',
        ),
        migrations.AlterField(
            model_name='history',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
