# Generated by Django 2.0.2 on 2018-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0002_remove_inspector_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='home_state',
            field=models.CharField(blank=True, choices=[('Pennsylvania', 'PA'), ('New Jersey', 'NJ'), ('Delaware', 'DE'), ('Maryland', 'MD'), ('Ohio', 'OH'), ('New York', 'NY')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='office',
            field=models.CharField(choices=[('King of Prussia', 'KOP'), ('Pittsburgh', 'PGH'), ('Test', 'TEST'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
